Verdezul.SYSOSP.Web/Areas/Verdezul/Models/LogDBViewModel.cs
using System;
using System.Collections.Generic;
using System.IO;
using Verdezul.SYSOSP.Web.Areas.Verdezul.Controllers;
using Verdezul.SYSOSP.Web.Entities;

namespace Verdezul.SYSOSP.Web.Areas.Verdezul.Models
{
    public class LogDBViewModel
    {
        public List<LogDB> Item { get; set; }
        public TipoMantenimiento TipoMantenimiento { get; set; }
        public TipoLogDB Tipo { get; set; }
        public String Tabla { get; set; }
        public int PedidoID { get; set; }
        public int ClienteID { get; set; }
    }

    public class LogErrorViewModel
    {
        public LogErrorViewModel()
        {
            Archivos = new List<string>();
            Renombramientos = new List<Renombramiento>();
        }
        
        public TipoLogError Tipo { get; set; }
        public List<string> Archivos { get; set; }

        public List<Renombramiento> Renombramientos { get; set; }
        public List<string> Lineas { get; set; }
        public string NombreArchivo { get; set; }
        public FileInfo FileInfo { get; set; }
    }

    public enum TipoLogDB
    {
        Tabla = 1,
        Pedido = 2,
        Cliente = 3
    }

    public enum TipoLogError
    {
        Lista = 1,
        Detalle = 2
    }
}

Verdezul.SYSOSP.Web/Entities/LogDB.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Verdezul.SYSOSP.Web.Entities
{
    [Table("LogDB")]
    public class LogDB
    {
        public int ID { get; set; }
        public String Tabla { get; set; }
        public int EntityID { get; set; }
        public int? PedidoID { get; set; }
        public int? OrdenTrabajoID { get; set; }
        public int? AnalisisMuestraID { get; set; }
        public int? ClienteID { get; set; }
        public DateTime EntityDate { get; set; }
        public EstadoEntidad Status { get; set; }
        public String User { get; set; }
    }
}

Verdezul.SYSOSP.Web/Areas/Verdezul/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using Verdezul.SYSOSP.Web.Areas.Admin.Models;
using Verdezul.SYSOSP.Web.Areas.Verdezul.Models;
using Verdezul.SYSOSP.Web.DAL;
using Verdezul.SYSOSP.Web.Entities;
using Verdezul.SYSOSP.Web.Helpers;

namespace Verdezul.SYSOSP.Web.Areas.Verdezul.Controllers
{
    [Authorize(Users = Constantes.USR_SUPAD)]
    public class LogController : Controller
    {
        protected ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return RedirectToAction("DB");
        }

        public ActionResult DB()
        {
            var model = new LogDBViewModel
            {
                Tipo = TipoLogDB.Tabla,
                Item = new List<LogDB>()
            };
            return View("LogDB", model);
        }

        [HttpPost]
        public ActionResult DB(LogDBViewModel model)
        {
            List<LogDB> logs = new List<LogDB>();
            switch (model.Tipo)
            {
                case TipoLogDB.Tabla:
                    model.Item = db.LogDBs.Where(x => x.Tabla == model.Tabla).OrderBy(y => y.EntityDate).ToList();
                    break;
                case TipoLogDB.Pedido:
                    model.Item = db.LogDBs.Where(x => x.PedidoID == model.PedidoID).OrderBy(y => y.EntityDate).ToList();
                    break;
                case TipoLogDB.Cliente:
                    model.Item = db.LogDBs.Where(x => x.ClienteID == model.ClienteID).OrderBy(y => y.EntityDate).ToList();
                    break;
            }
            return View("LogDB", model);
        }

        public ActionResult Error()
        {
            string carpetaLog = Server.MapPath(Constantes.CAR_LOGS);

            LogErrorViewModel model = new LogErrorViewModel { 
                Archivos = Directory.GetFiles(carpetaLog).Select(x => x.Replace($"{carpetaLog}\\", "")).Where(y => !y.Contains("empty")).ToList(),
                Tipo = TipoLogError.Lista
            };
            return View("LogError", model);
        }

        public ActionResult ErrorDetail(string file)
        {
            string carpetaLog = Server.MapPath(Constantes.CAR_LOGS);

            LogErrorViewModel model = new LogErrorViewModel { 
                Lineas = System.IO.File.ReadAllLines($"{carpetaLog}/{file}").ToList(),
                NombreArchivo = file,
                Tipo = TipoLogError.Detalle
            };

            return View("LogError", model);
        }

        [HttpPost]
        public ActionResult LimpiarLogs()
        {
            string carpetaLog = Server.MapPath(Constantes.CAR_LOGS);

            foreach(var archivo in Directory.GetFiles(carpetaLog))
            {
                if (!archivo.Contains("empty"))
                    System.IO.File.Delete(archivo);
            }
            
            var result = 0;
            return Json(new { status = result });
        }

        public ActionResult Files()
        {
            string carpetaArchivos = Server.MapPath(Constantes.CAR_ARCHI);

            LogErrorViewModel model = new LogErrorViewModel
            {
                Archivos = Directory.GetFiles(carpetaArchivos).Where(p => !p.Contains("empty")).Select(x => x.Replace($"{carpetaArchivos}\\", "")).ToList(),
                Tipo = TipoLogError.Lista
            };
            return View("LogFiles", model);
        }

        public ActionResult FileDetail(string fileName)
        {
            string carpetaArchivos = Server.MapPath(Constantes.CAR_ARCHI);

            FileInfo fi = new FileInfo($"{carpetaArchivos}/{fileName}");

            LogErrorViewModel model = new LogErrorViewModel
            {
                FileInfo = fi,
                Tipo = TipoLogError.Detalle
            };
            return View("LogFiles", model);
        }

        public ActionResult FileDownload(string fileName)
        {

            FileInfo fileInfo = new FileInfo(Server.MapPath($"{Constantes.CAR_ARCHI}/{fileName}"));
            byte[] fileBytes = System.IO.File.ReadAllBytes(fileInfo.FullName);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area Area = db.Areas.Find(id);
            if (Area == null)
            {
                return HttpNotFound();
            }
            return View(Area);
        }

        public ActionResult TestCorreo()
        {
            var result = EmailHelper.SendMail(EmailHelper.PlantillaTest(), new MimeKit.MailboxAddress("Correo SYSOSP Test", ConfigurationManager.AppSettings["CorreoVerificacion"]), "Test");

            if (result != SendMailResult.Enviado)
                throw new SmtpException($"Testing {result}");
            else
            {
                EnvioCorreoDAL.GrabarEnvioCorreo(TipoNotificacion.Otros, null, null, "Correo SYSOSP Test", ConfigurationManager.AppSettings["CorreoVerificacion"]);
            }

            return View(new CorreoViewModel { MensajeProcedimiento = "Probando" });
        }
    }
}

Verdezul.SYSOSP.Web/Areas/Verdezul/Views/Log/LogDB.cshtml
@model LogDBViewModel

@{
    ViewBag.Title = "Listado LogDB";

    var tablas = new List<String> {
        "Clientes",
        "Areas",
        "Parametros",
        "SubAnalisisMuestra",
        "AnalisisMuestra",
        "OrdenesTrabajo",
        "Archivos",
        "FechasPedido",
        "Muestras",
        "Pedidos",
        "EnviosCorreo",
        "PagosContrato",
        "Plantillas",
        "Bioquimicos",
        "GruposAnalisis",
        "Analisis",
        "SubAnalisis",
        "DetallesPlantilla",
    }.Select(x => new SelectListItem { Text = x, Value = x }).OrderBy(x => x.Text);
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(x => x.Tipo, new { @class = "form-control" })
            </div>
            @Html.LabelFor(model => model.Tabla, htmlAttributes: new { @class = "control-label col-md-2 parametro parametro-tabla" })
            <div class="col-md-10 parametro parametro-tabla">
                @Html.DropDownListFor(x => x.Tabla, tablas, new { @class = "form-control" })
            </div>
            @Html.LabelFor(model => model.PedidoID, htmlAttributes: new { @class = "control-label col-md-2 parametro parametro-pedido" })
            <div class="col-md-10 parametro parametro-pedido">
                @Html.TextBoxFor(x => x.PedidoID, new { @class = "form-control", type = "number" })
            </div>
            @Html.LabelFor(model => model.ClienteID, htmlAttributes: new { @class = "control-label col-md-2 parametro parametro-cliente" })
            <div class="col-md-10 parametro parametro-cliente">
                @Html.TextBoxFor(x => x.ClienteID, new { @class = "form-control", type = "number" })
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Revisar" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

@if (Model.Item.Count() > 0)
{
    switch (Model.Tipo)
    {
        case TipoLogDB.Tabla:
            <table class="table">
                <tr>
                    <th>Tabla</th>
                    <th>ID</th>
                    <th>EntityDate</th>
                    <th>Status</th>
                    <th>User</th>
                </tr>

                @foreach (var item in Model.Item)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Tabla)</td>
                        <td>@Html.DisplayFor(modelItem => item.EntityID)</td>
                        <td>@Html.DisplayFor(modelItem => item.EntityDate)</td>
                        <td>@Html.DisplayFor(modelItem => item.Status)</td>
                        <td>@Html.DisplayFor(modelItem => item.User)</td>
                    </tr>
                }
            </table>
            break;
        case TipoLogDB.Pedido:
            <table class="table">
                <tr>
                    <th>Tabla</th>
                    <th>ID</th>
                    <th>PedidoID</th>
                    <th>OrdenTrabajoID</th>
                    <th>AnalisisMuestraID</th>
                    <th>EntityDate</th>
                    <th>Status</th>
                    <th>User</th>
                </tr>

                @foreach (var item in Model.Item)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Tabla)</td>
                        <td>@Html.DisplayFor(modelItem => item.EntityID)</td>
                        <td>@Html.DisplayFor(modelItem => item.PedidoID)</td>
                        <td>@Html.DisplayFor(modelItem => item.OrdenTrabajoID)</td>
                        <td>@Html.DisplayFor(modelItem => item.AnalisisMuestraID)</td>
                        <td>@Html.DisplayFor(modelItem => item.EntityDate)</td>
                        <td>@Html.DisplayFor(modelItem => item.Status)</td>
                        <td>@Html.DisplayFor(modelItem => item.User)</td>
                    </tr>
                }
            </table>
            break;
        case TipoLogDB.Cliente:
            <table class="table">
                <tr>
                    <th>ClienteID</th>
                    <th>Tabla</th>
                    <th>ID</th>
                    <th>EntityDate</th>
                    <th>Status</th>
                    <th>User</th>
                </tr>

                @foreach (var item in Model.Item)
                {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.ClienteID)</td>
                <td>@Html.DisplayFor(modelItem => item.Tabla)</td>
                <td>@Html.DisplayFor(modelItem => item.EntityID)</td>
                <td>@Html.DisplayFor(modelItem => item.EntityDate)</td>
                <td>@Html.DisplayFor(modelItem => item.Status)</td>
                <td>@Html.DisplayFor(modelItem => item.User)</td>
            </tr>
                }
            </table>
            break;

    }
}

@section scripts {
    <script>
        xyz($('#Tipo').val());
        $('#Tipo').change(function () {
            xyz($('#Tipo').val());
        });

        function xyz(tipo) {
            $('.parametro').hide();
            switch (tipo) {
                case "1":
                    $('.parametro-tabla').show();
                    break;
                case "2":
                    $('.parametro-pedido').show();
                    break;
                case "3":
                    $('.parametro-cliente').show();
                    break;
            }
        }
    </script>
}

Verdezul.SYSOSP.Web/Areas/Verdezul/Views/Log/LogError.cshtml
@model LogErrorViewModel

@{
    ViewBag.Title = $"{Model.Tipo} LogError";
}

<h2>@ViewBag.Title</h2>

@switch (Model.Tipo)
{
    case TipoLogError.Lista:
        <table class="table">
            @foreach (var archivo in Model.Archivos)
            {
                <tr>
                    <td>@archivo</td>
                    <td>@Html.ActionLink("Ver", "ErrorDetail", new { file = archivo })</td>
                </tr>
            }
        </table>

        <input type="button" class="btn btn-default" value="Limpiar Logs" id="limpiarLogs" />

        break;

    case TipoLogError.Detalle:
        <h2>@Model.NombreArchivo.Replace(".txt", "")</h2>

        foreach (var linea in Model.Lineas)
        {
            <p>@linea</p>
        }

        @Html.ActionLink("Regresar a Listado", "Error")
        break;

}

@section Scripts {
    <script>
        $('#limpiarLogs').click(function () {
            HabilitarBoton($(this), false);
            var url = '@Url.Content("~/LogDB/LimpiarLogs")';
            $.ajax({
                type: "POST",
                url: url,
                success: function (data) {
                    location.reload(true);
                },
                error: function (r) {
                    alert("Error del servidor");
                },
                complete: function(e) {
                    HabilitarBoton($('#notificarResultadosParciales'), true);
                }
            });

        });

        function HabilitarBoton($boton, habilitar) {
            if (!habilitar) {
                $boton.attr("disabled", "disabled").val("Limpiando...")
            } else {
                $boton.removeAttr("disabled").val($boton.attr("data-initialvalue"));
            }
        }
    </script>
}

Verdezul.SYSOSP.Web/Areas/Verdezul/Views/Log/LogFiles.cshtml
@model LogErrorViewModel

@{
    ViewBag.Title = $"{Model.Tipo} LogFiles";
}

<h2>@ViewBag.Title</h2>

@switch (Model.Tipo)
{
    case TipoLogError.Lista:
        <table class="table">
            <tr>
                <th>FileName</th>
                <th>Tipo</th>
                <th>PedidoID</th>
                <th>OrdenTrabajoID</th>
                <th>MuestraID</th>
                <th>Extension</th>
                <th colspan="2"></th>
            </tr>
            @foreach (var nombreArchivo in Model.Archivos)
            {
                Archivo archivo = Archivo.SetArchivoFromName(nombreArchivo);
                <tr>
                    <td>@nombreArchivo</td>
                    <td>@archivo.Tipo.ToDisplayName()</td>
                    <td>@archivo.PedidoID</td>
                    <td>@archivo.IdOrdenTrabajo</td>
                    <td>@archivo.IdMuestra</td>
                    <td>@archivo.Extension</td>
                    <td>@Html.ActionLink(" ", "FileDetail", new { fileName = nombreArchivo }, new { @class="fa fa-eye" })</td>
                    <td><a target="_blank" href="@Url.Action("FileDownload", "Log", new { area = "Verdezul", fileName = nombreArchivo })" class="fa fa-download"></a></td>
                </tr>
            }
        </table>

        break;

    case TipoLogError.Detalle:
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>@Model.FileInfo.Name</dd>

            <dt>CreationTimeUtc</dt>
            <dd>@Model.FileInfo.CreationTimeUtc</dd>

            <dt>Length</dt>
            <dd>@Model.FileInfo.Length</dd>

            <dt>Extension</dt>
            <dd>@Model.FileInfo.Extension</dd>

            <dt>LastAccessTimeUtc</dt>
            <dd>@Model.FileInfo.LastAccessTimeUtc</dd>

            <dt>LastWriteTime</dt>
            <dd>@Model.FileInfo.LastWriteTime</dd>

            <dt>IsReadOnly</dt>
            <dd>@Model.FileInfo.IsReadOnly</dd>

            <dt>Attributes</dt>
            <dd>@Model.FileInfo.Attributes</dd>

            <dt></dt>
            <dd><a target="_blank" href="@Url.Action("FileDownload", "Log", new { area = "Verdezul", fileName = Model.FileInfo.Name })"> Descargar </a></dd>
        </dl>

        @Html.ActionLink("Regresar a listado", "Files")
        break;
}

Verdezul.SYSOSP.Web/Areas/Verdezul/Views/Log/TestCorreo.cshtml
@model Verdezul.SYSOSP.Web.Areas.Admin.Models.CorreoViewModel
@{
    ViewBag.Title = "Probando Correo";
}

<h2>@ViewBag.Title</h2>

<h3>@Model.MensajeProcedimiento</h3>